#!/usr/bin/env python3
"""
Extract lightweight per-card render data from the vendored .ghostline recordings.

Emits `card-data.js` — a single JS global the demo-library page reads to draw a
mini 3D token-cloud on each recording card. Coordinates are centered on each
recording's centroid and normalized to roughly [-1, 1] so the renderer needs no
per-card tuning.

Re-run whenever the recordings change:
    python static-landing/extract_card_data.py
"""
import json
import math
import pathlib
import collections

HERE = pathlib.Path(__file__).resolve().parent
RECDIR = HERE.parent / "demo-app" / "recordings"
OUT = HERE / "card-data.js"

# Card display order matches demo-library.html
ORDER = [
    "hallucination-detection",
    "math-reasoning",
    "knowledge-retrieval",
    "moral-reasoning",
    "code-generation",
    "ai-overview",
    "chicken",
]

# geometricState -> short code (keeps the data file small)
STATE_CODE = {
    "reasoning": "R",
    "retrieval": "T",
    "creativity": "C",
    "precision": "P",
    "uncertainty": "U",
    "collapse": "X",
    "edge_cases": "E",
    "unknown": "?",
}


def extract(name: str):
    path = RECDIR / f"{name}.ghostline"
    data = json.loads(path.read_bytes())
    gen = [fr for fr in data["trajectory"] if not fr.get("isPrompt", False)]

    xs = [fr["coords"][0] for fr in gen]
    ys = [fr["coords"][1] for fr in gen]
    zs = [fr["coords"][2] for fr in gen]
    cx, cy, cz = sum(xs) / len(xs), sum(ys) / len(ys), sum(zs) / len(zs)

    # Normalize by 95th-percentile radius so a single outlier token can't
    # shrink the whole cloud into a dot.
    radii = sorted(
        math.sqrt((x - cx) ** 2 + (y - cy) ** 2 + (z - cz) ** 2)
        for x, y, z in zip(xs, ys, zs)
    )
    scale = radii[int(len(radii) * 0.95)] or 1.0

    pts = []
    states = collections.Counter()
    risk_max = 0.0
    for fr in gen:
        x, y, z = fr["coords"]
        st = fr.get("geometricState", "unknown")
        states[st] += 1
        code = STATE_CODE.get(st, "?")
        risk = fr.get("hallucinationRisk")
        nx = round((x - cx) / scale, 3)
        ny = round((y - cy) / scale, 3)
        nz = round((z - cz) / scale, 3)
        # Only carry a risk value when it's meaningful (keeps file small).
        if risk is not None and risk >= 0.5:
            pts.append([nx, ny, nz, code, round(risk, 2)])
            risk_max = max(risk_max, risk)
        else:
            pts.append([nx, ny, nz, code])

    return pts, states, risk_max


def main():
    out = {}
    print("Extracting card render data:\n")
    for name in ORDER:
        pts, states, risk_max = extract(name)
        out[name] = pts
        state_str = ", ".join(f"{s}:{n}" for s, n in states.most_common())
        print(f"  {name}: {len(pts)} pts | {state_str} | risk_max={risk_max:.2f}")

    payload = json.dumps(out, separators=(",", ":"))
    OUT.write_text(
        "/* AUTO-GENERATED by extract_card_data.py — do not edit by hand. */\n"
        "window.GHOSTLINE_CARD_DATA = " + payload + ";\n",
        encoding="utf-8",
    )
    size_kb = OUT.stat().st_size / 1024
    print(f"\nWrote {OUT.name} ({size_kb:.1f} KB)")


if __name__ == "__main__":
    main()
